title: CS-205M
description: Official website for CS-205M(Theoritical Foundation of Computer Science) lectures and resources.
#theme:  jekyll-theme-primer # You can choose other themes like jekyll-theme-cayman, jekyll-theme-architect, etc.



exclude:
  - README.md
  - .gitignore
